### ISSUE TITLE
Implement ability to use luster with babel-node

### ISSUE THREAD

**Issue by dfilatov** [nodules/luster#29]
It's very handy to use `babel-node` wrapper during development. But I couldn't find a way to use it with luster. Maybe I've missed something, have I?

cc @narqo

**Comment by Flackus** [comment]
Had no chance to try it yet, but it should work, if your `worker.js`-file is ES5, while all subsequent requires occured after `require('babel/register')` will be transformed nicely.

**worker.js** (only ES5 is allowed)
```
require("babel/register");
// after this line required files should be transformed properly
var es6_stuff = require("./es6_stuff.js");
```

But I presume you've already tried that?

**Comment by dfilatov** [comment]
There's a simple way to use `babel-node` with `luster` via `babel-node -- luster luster.conf.js` (thanks to @narqo for suggest).
There's another problem — plugin `luster-guard` is hanging with `restarting workers...`. I'll open corresponding issue in its tracker and close this issue.
