### ISSUE TITLE
luster ignores debug port from config file

### ISSUE THREAD

**Issue by bu1ka** [nodules/luster#34]
in config file sets
```
debug: {
        port: 9000
}
```
but worker starts with default debug port 
```
www-data 17921  0.1  9.9 2375784 203404 ?      Sl   13:08   0:06 /opt/nodejs/4/bin/node --debug=5859 /node_modules/.bin/luster configs/luster.js
```

**Comment by narqo** [comment]
Looks like the behaviour of Node.js has changed. They always use `process.debugPort` port value no matter what was passed to the `execArgv`. See [`createWorkerProcess()` function of node.js v4.x](https://github.com/nodejs/node/blob/v4.x/lib/cluster.js#L287-L302).

**Comment by kaero** [comment]
The `debug.port` option was a way to hack the debug port definition for forked workers for previous versions of Node.js. It's not used and must not be used for Node.js 0.12+, afaik. I suggest to mention this behavior in the readme as fix of this issue.
